version: '2'

services:
 rasterfari-bpl-prep:
  image: cismet/rasterfari-tile-prep-bplaene:latest
  network_mode: bridge
  volumes:
   - ./.zshrc:/root/.zshrc
   - ./.zsh_history:/root/.zsh_history
   - ./_tmp:/app/pictmpdir
   - ./_tmp:/app/_tmp
   - ./policy.xml:/etc/ImageMagick-6/policy.xml:ro
   - ./_in:/app/_in
   - ./_internal:/app/_internal
   - ./_out:/app/_out
   - ./_logs:/app/_logs
   - ./_tilesstoragemount:/app/_tilesstoragemount
   - ./crontab:/etc/cron/crontab
   ## use this only in dev
   - ./src:/app/src
   - ./package.json:/app/package.json
  
  restart: always
  extra_hosts:
   -  "aaa.cismet.de:88.99.101.202"
  ## the default command will run rasterfari with 20 threads
  #command: /bin/bash #yarn run dev-run
